labtainer_instructor.pdf: labtainer_instructor.tex
	pdflatex labtainer_instructor
	pdflatex labtainer_instructor
clean:
	rm -fr auto
	rm -fr labtainer_instructor.aux labtainer_instructor.pdf *.ps *.dvi
