all: labtainer_student.pdf


labtainer_student.pdf: InstallingVB-LinuxWin.pdf labtainer_student.tex
	pdflatex labtainer_student
	pdflatex labtainer_student
clean:
	rm -fr auto
	rm -fr labtainer_student.aux labtainer_student.pdf *.ps *.dvi
